/*
testing-step

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseStepDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseStepDto{}

// BaseStepDto struct for BaseStepDto
type BaseStepDto struct {
	Id string `json:"id"`
	Key string `json:"key"`
	Name string `json:"name"`
	JobId string `json:"jobId"`
	MilestoneId string `json:"milestoneId"`
	DependedOnBy []string `json:"dependedOnBy"`
	DependsOn []string `json:"dependsOn"`
}

type _BaseStepDto BaseStepDto

// NewBaseStepDto instantiates a new BaseStepDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseStepDto(id string, key string, name string, jobId string, milestoneId string, dependedOnBy []string, dependsOn []string) *BaseStepDto {
	this := BaseStepDto{}
	this.Id = id
	this.Key = key
	this.Name = name
	this.JobId = jobId
	this.MilestoneId = milestoneId
	this.DependedOnBy = dependedOnBy
	this.DependsOn = dependsOn
	return &this
}

// NewBaseStepDtoWithDefaults instantiates a new BaseStepDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseStepDtoWithDefaults() *BaseStepDto {
	this := BaseStepDto{}
	return &this
}

// GetId returns the Id field value
func (o *BaseStepDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BaseStepDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BaseStepDto) SetId(v string) {
	o.Id = v
}

// GetKey returns the Key field value
func (o *BaseStepDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *BaseStepDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *BaseStepDto) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *BaseStepDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BaseStepDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BaseStepDto) SetName(v string) {
	o.Name = v
}

// GetJobId returns the JobId field value
func (o *BaseStepDto) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *BaseStepDto) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *BaseStepDto) SetJobId(v string) {
	o.JobId = v
}

// GetMilestoneId returns the MilestoneId field value
func (o *BaseStepDto) GetMilestoneId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MilestoneId
}

// GetMilestoneIdOk returns a tuple with the MilestoneId field value
// and a boolean to check if the value has been set.
func (o *BaseStepDto) GetMilestoneIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MilestoneId, true
}

// SetMilestoneId sets field value
func (o *BaseStepDto) SetMilestoneId(v string) {
	o.MilestoneId = v
}

// GetDependedOnBy returns the DependedOnBy field value
func (o *BaseStepDto) GetDependedOnBy() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DependedOnBy
}

// GetDependedOnByOk returns a tuple with the DependedOnBy field value
// and a boolean to check if the value has been set.
func (o *BaseStepDto) GetDependedOnByOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DependedOnBy, true
}

// SetDependedOnBy sets field value
func (o *BaseStepDto) SetDependedOnBy(v []string) {
	o.DependedOnBy = v
}

// GetDependsOn returns the DependsOn field value
func (o *BaseStepDto) GetDependsOn() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DependsOn
}

// GetDependsOnOk returns a tuple with the DependsOn field value
// and a boolean to check if the value has been set.
func (o *BaseStepDto) GetDependsOnOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DependsOn, true
}

// SetDependsOn sets field value
func (o *BaseStepDto) SetDependsOn(v []string) {
	o.DependsOn = v
}

func (o BaseStepDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseStepDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	toSerialize["jobId"] = o.JobId
	toSerialize["milestoneId"] = o.MilestoneId
	toSerialize["dependedOnBy"] = o.DependedOnBy
	toSerialize["dependsOn"] = o.DependsOn
	return toSerialize, nil
}

func (o *BaseStepDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key",
		"name",
		"jobId",
		"milestoneId",
		"dependedOnBy",
		"dependsOn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseStepDto := _BaseStepDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseStepDto)

	if err != nil {
		return err
	}

	*o = BaseStepDto(varBaseStepDto)

	return err
}

type NullableBaseStepDto struct {
	value *BaseStepDto
	isSet bool
}

func (v NullableBaseStepDto) Get() *BaseStepDto {
	return v.value
}

func (v *NullableBaseStepDto) Set(val *BaseStepDto) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseStepDto) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseStepDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseStepDto(val *BaseStepDto) *NullableBaseStepDto {
	return &NullableBaseStepDto{value: val, isSet: true}
}

func (v NullableBaseStepDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseStepDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


