/*
testing-step

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TestingStepV1FailedStepDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestingStepV1FailedStepDto{}

// TestingStepV1FailedStepDto struct for TestingStepV1FailedStepDto
type TestingStepV1FailedStepDto struct {
	Id string `json:"id"`
	Key string `json:"key"`
	Name string `json:"name"`
	JobId string `json:"jobId"`
	MilestoneId string `json:"milestoneId"`
	DependedOnBy []string `json:"dependedOnBy"`
	DependsOn []string `json:"dependsOn"`
	StepType TestingStepV1StepType `json:"stepType"`
	Parameters map[string]string `json:"parameters"`
	Status TestingStepV1StepStatus `json:"status"`
	Result TestingStepV1FailedResult `json:"result"`
}

type _TestingStepV1FailedStepDto TestingStepV1FailedStepDto

// NewTestingStepV1FailedStepDto instantiates a new TestingStepV1FailedStepDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestingStepV1FailedStepDto(id string, key string, name string, jobId string, milestoneId string, dependedOnBy []string, dependsOn []string, stepType TestingStepV1StepType, parameters map[string]string, status TestingStepV1StepStatus, result TestingStepV1FailedResult) *TestingStepV1FailedStepDto {
	this := TestingStepV1FailedStepDto{}
	this.Id = id
	this.Key = key
	this.Name = name
	this.JobId = jobId
	this.MilestoneId = milestoneId
	this.DependedOnBy = dependedOnBy
	this.DependsOn = dependsOn
	this.StepType = stepType
	this.Parameters = parameters
	this.Status = status
	this.Result = result
	return &this
}

// NewTestingStepV1FailedStepDtoWithDefaults instantiates a new TestingStepV1FailedStepDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestingStepV1FailedStepDtoWithDefaults() *TestingStepV1FailedStepDto {
	this := TestingStepV1FailedStepDto{}
	return &this
}

// GetId returns the Id field value
func (o *TestingStepV1FailedStepDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TestingStepV1FailedStepDto) SetId(v string) {
	o.Id = v
}

// GetKey returns the Key field value
func (o *TestingStepV1FailedStepDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *TestingStepV1FailedStepDto) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *TestingStepV1FailedStepDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TestingStepV1FailedStepDto) SetName(v string) {
	o.Name = v
}

// GetJobId returns the JobId field value
func (o *TestingStepV1FailedStepDto) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *TestingStepV1FailedStepDto) SetJobId(v string) {
	o.JobId = v
}

// GetMilestoneId returns the MilestoneId field value
func (o *TestingStepV1FailedStepDto) GetMilestoneId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MilestoneId
}

// GetMilestoneIdOk returns a tuple with the MilestoneId field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetMilestoneIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MilestoneId, true
}

// SetMilestoneId sets field value
func (o *TestingStepV1FailedStepDto) SetMilestoneId(v string) {
	o.MilestoneId = v
}

// GetDependedOnBy returns the DependedOnBy field value
func (o *TestingStepV1FailedStepDto) GetDependedOnBy() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DependedOnBy
}

// GetDependedOnByOk returns a tuple with the DependedOnBy field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetDependedOnByOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DependedOnBy, true
}

// SetDependedOnBy sets field value
func (o *TestingStepV1FailedStepDto) SetDependedOnBy(v []string) {
	o.DependedOnBy = v
}

// GetDependsOn returns the DependsOn field value
func (o *TestingStepV1FailedStepDto) GetDependsOn() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DependsOn
}

// GetDependsOnOk returns a tuple with the DependsOn field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetDependsOnOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DependsOn, true
}

// SetDependsOn sets field value
func (o *TestingStepV1FailedStepDto) SetDependsOn(v []string) {
	o.DependsOn = v
}

// GetStepType returns the StepType field value
func (o *TestingStepV1FailedStepDto) GetStepType() TestingStepV1StepType {
	if o == nil {
		var ret TestingStepV1StepType
		return ret
	}

	return o.StepType
}

// GetStepTypeOk returns a tuple with the StepType field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetStepTypeOk() (*TestingStepV1StepType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StepType, true
}

// SetStepType sets field value
func (o *TestingStepV1FailedStepDto) SetStepType(v TestingStepV1StepType) {
	o.StepType = v
}

// GetParameters returns the Parameters field value
func (o *TestingStepV1FailedStepDto) GetParameters() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetParametersOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *TestingStepV1FailedStepDto) SetParameters(v map[string]string) {
	o.Parameters = v
}

// GetStatus returns the Status field value
func (o *TestingStepV1FailedStepDto) GetStatus() TestingStepV1StepStatus {
	if o == nil {
		var ret TestingStepV1StepStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetStatusOk() (*TestingStepV1StepStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TestingStepV1FailedStepDto) SetStatus(v TestingStepV1StepStatus) {
	o.Status = v
}

// GetResult returns the Result field value
func (o *TestingStepV1FailedStepDto) GetResult() TestingStepV1FailedResult {
	if o == nil {
		var ret TestingStepV1FailedResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *TestingStepV1FailedStepDto) GetResultOk() (*TestingStepV1FailedResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *TestingStepV1FailedStepDto) SetResult(v TestingStepV1FailedResult) {
	o.Result = v
}

func (o TestingStepV1FailedStepDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestingStepV1FailedStepDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	toSerialize["jobId"] = o.JobId
	toSerialize["milestoneId"] = o.MilestoneId
	toSerialize["dependedOnBy"] = o.DependedOnBy
	toSerialize["dependsOn"] = o.DependsOn
	toSerialize["stepType"] = o.StepType
	toSerialize["parameters"] = o.Parameters
	toSerialize["status"] = o.Status
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *TestingStepV1FailedStepDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key",
		"name",
		"jobId",
		"milestoneId",
		"dependedOnBy",
		"dependsOn",
		"stepType",
		"parameters",
		"status",
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTestingStepV1FailedStepDto := _TestingStepV1FailedStepDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTestingStepV1FailedStepDto)

	if err != nil {
		return err
	}

	*o = TestingStepV1FailedStepDto(varTestingStepV1FailedStepDto)

	return err
}

type NullableTestingStepV1FailedStepDto struct {
	value *TestingStepV1FailedStepDto
	isSet bool
}

func (v NullableTestingStepV1FailedStepDto) Get() *TestingStepV1FailedStepDto {
	return v.value
}

func (v *NullableTestingStepV1FailedStepDto) Set(val *TestingStepV1FailedStepDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTestingStepV1FailedStepDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTestingStepV1FailedStepDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestingStepV1FailedStepDto(val *TestingStepV1FailedStepDto) *NullableTestingStepV1FailedStepDto {
	return &NullableTestingStepV1FailedStepDto{value: val, isSet: true}
}

func (v NullableTestingStepV1FailedStepDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestingStepV1FailedStepDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


